CREATE DATABASE AdvancedCriteria DEFAULT CHARACTER SET 'utf8'
  DEFAULT COLLATE 'utf8_unicode_ci';

USE AdvancedCriteria;

CREATE TABLE Person (
  PersonId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FirstName VARCHAR(100) NOT NULL,
  MiddleInitial CHAR(1) NOT NULL,
  LastName VARCHAR(100) NOT NULL,
  State VARCHAR(100) NOT NULL,
  Country VARCHAR(100) NOT NULL,
  BirthDate DATE NOT NULL,
  Gender ENUM('MALE', 'FEMALE', 'UNSPECIFIED') NOT NULL,
  Race VARCHAR(30) NOT NULL,
  Ethnicity VARCHAR(50) NOT NULL
) ENGINE = InnoDB;
